services:
  - name: web
    type: web
    runtime: python
    envVars:
      - key: CLOUDSDK_CORE_PROJECT
        value: "predictorDiabetes"
      - key: GOOGLE_APPLICATION_CREDENTIALS 
        value: "/etc/secrets/predictordiabetes-eac5e9c634e7.json"
    startCommand: "./venv/bin/gunicorn app:app"
    plan: free